version: '3.8'

services:
  prodbuddy_api:
    build: .
    container_name: prodbuddy_container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always # Ensures container restarts if it crashes
    env_file:
      - .env
